/*
 * Cross-language contract test.
 *
 * Three Swift↔TS contract drifts have shipped on this project, each invisible in `npm run dev`
 * because the dev mock sent the client's shape while the engine sent something else:
 *   1. engine injected `__DAILY_PLANNER_TOKEN__`, client read `__DP_TOKEN__`
 *   2. engine's TaskDTO had no `done`, client required it
 *   3. engine's DraftDTO was {subject,recipient,body,…}, client read {id,title,summary,kind}
 * Every layer was unit tested. The seam between the two languages was not.
 *
 * `engine-contract.json` is GENERATED by the Swift suite
 * (DailyPlannerAPITests/EngineContractFixtureTests) from the real encoders — every route's
 * actual JSON and every finite enum's real cases. These assertions run against that, not
 * against a hand-maintained mock, so the mock can no longer drift quietly.
 *
 * If one of these fails after a Swift change, the TypeScript side is out of date — that is the
 * point. Run the Swift suite first to regenerate, then `npm test`.
 */

import { describe, expect, it } from "vitest";

import contract from "./__fixtures__/engine-contract.json";
import { api, CATEGORIES } from "./client";
import { presentationFor, kindLabel } from "../lib/category";

const enums = contract.enums as Record<string, string[]>;
const routes = contract.routes as Record<string, any>;
const variants = (contract as any).variants as Record<string, any>;

describe("finite enums match the engine", () => {
  it("knows every category the engine can send", () => {
    expect([...CATEGORIES].sort()).toEqual([...enums.category].sort());
  });

  it("gives every engine category its own presentation", () => {
    // The real failure mode was silence: `presentationFor` has a `default` arm, so a category
    // the client had never heard of rendered as "Other" with the neutral colour instead of
    // failing. `commute` and `work` did exactly that.
    const tags = enums.category.map((category) =>
      presentationFor({ category: category as never, kind: "event" }).tag,
    );
    expect(new Set(tags).size).toBe(enums.category.length);
    expect(tags).not.toContain(undefined);
  });

  it("labels every event kind the engine can send", () => {
    for (const kind of enums.kind) {
      expect(kindLabel(kind as never)).toBeTruthy();
    }
  });

  it("uses the calendar roles the engine encodes", () => {
    expect([...enums.calendarRole].sort()).toEqual(["excluded", "planning"]);
  });
});

describe("every route carries the keys the client reads", () => {
  const requires = (value: any, keys: string[]) => {
    for (const key of keys) expect(Object.keys(value)).toContain(key);
  };

  it("/api/preview", () => {
    const preview = routes["/api/preview"];
    requires(preview, ["queue", "schedule", "day"]);
    for (const event of [...preview.queue, ...preview.schedule]) {
      // `end`, `due` and `location` are `string | null`: the KEY must exist even when null,
      // because the client distinguishes "absent" from "null".
      requires(event, [
        "id",
        "title",
        "category",
        "kind",
        "start",
        "end",
        "due",
        "location",
        // Without this key an event cannot be moved — it is the calendar the PATCH goes to.
        // Its absence is what limited "Move it" to inserting a duplicate.
        "calendarId",
      ]);
      expect(CATEGORIES).toContain(event.category);
      expect(enums.kind).toContain(event.kind);
      expect(typeof event.calendarId).toBe("string");
      expect(event.calendarId.length).toBeGreaterThan(0);
    }
  });

  it("/api/tasks — the DTO that once shipped without `done`", () => {
    for (const list of routes["/api/tasks"].lists) {
      requires(list, ["name", "items"]);
      for (const item of list.items) {
        requires(item, ["id", "title", "category", "due", "done"]);
        expect(typeof item.done).toBe("boolean");
      }
    }
  });

  it("/api/drafts — the DTO that once shipped as {subject,recipient,body}", () => {
    for (const draft of routes["/api/drafts"].drafts) {
      requires(draft, ["id", "title", "summary", "kind"]);
      expect(typeof draft.title).toBe("string");
    }
    // The KEY must exist even on the synthetic path, where nothing is hidden. The client reads
    // it to say "14 promotions hidden"; undefined would silently become no note at all.
    expect(typeof routes["/api/drafts"].hiddenCount).toBe("number");
  });

  // The client posts to exactly these paths. If the engine renames one, the composer's request
  // would 404 at runtime with nothing here to catch it.
  it("the write routes the client posts to are the ones the engine serves", () => {
    expect([...enums.writeRoute].sort()).toEqual([
      "/api/calendar/events",
      "/api/calendar/events/move",
      "/api/mail/draft",
      "/api/mail/send",
      "/api/mail/summary",
    ]);
  });

  // The client maps four engine error codes to display text and treats the rest generically.
  // A new code the client has never heard of would silently fall back, which is the same
  // silent-default failure `commute`/`work` had.
  it("every write error code the engine can send is one the client handles", () => {
    const handled = ["invalid_request", "write_not_permitted", "provider_refused", "too_large"];
    for (const code of handled) expect(enums.errorCode).toContain(code);
  });

  it("/api/calendars", () => {
    for (const calendar of routes["/api/calendars"].calendars) {
      requires(calendar, ["id", "title", "role"]);
      expect(enums.calendarRole).toContain(calendar.role);
    }
  });

  it("/api/settings", () => {
    const settings = routes["/api/settings"];
    requires(settings, ["vaultSelected", "scanTimes", "safety", "source", "capability"]);
    expect(typeof settings.vaultSelected).toBe("boolean");
  });

  // `safety` was typed `Record<string, boolean>` on the TS side while the engine sent two
  // strings, and the dev mock sent a third shape again. It only went unnoticed because
  // SafetyRail hardcoded its wording — which it no longer does, so these fields are now the
  // literal text on screen. Assert each field's real type, not just its presence.
  it("/api/settings safety is fully typed, not a boolean bag", () => {
    const safety = routes["/api/settings"].safety;
    requires(safety, ["mode", "externalWrites", "label"]);
    expect(typeof safety.mode).toBe("string");
    expect(typeof safety.label).toBe("string");
    expect(typeof safety.externalWrites).toBe("boolean");
    // Sample data cannot write anywhere — there is nothing to write to.
    expect(safety.externalWrites).toBe(false);
    expect(safety.mode).toBe("read-only");
  });

  // The half that the synthetic fixture can never show. Without this, the engine could start
  // sending a mode or a label the client does not render and every test here would still pass.
  it("/api/settings tells the truth on a connection that CAN write", () => {
    const settings = variants.settingsWritable;
    expect(settings).toBeDefined();
    expect(settings.safety.mode).toBe("send-and-schedule");
    expect(settings.safety.externalWrites).toBe(true);
    expect(typeof settings.safety.label).toBe("string");
    // The label IS the safety rail's text now. An empty one is a rail that says nothing.
    expect(settings.safety.label.length).toBeGreaterThan(0);
    expect(settings.capability).toEqual({
      canSend: true,
      canSchedule: true,
      canReschedule: true,
      // False even on a full write grant: drafting needs an assistant on the machine, not a
      // permission from Google, and the contract fixture wires none.
      canDraft: false,
      canReadBody: false,
      canSummarize: false,
    });
  });

  it("/api/settings capability is booleans all the way, both ways", () => {
    for (const settings of [routes["/api/settings"], variants.settingsWritable]) {
      requires(settings.capability, ["canSend", "canSchedule", "canReschedule", "canDraft"]);
      expect(typeof settings.capability.canSend).toBe("boolean");
      expect(typeof settings.capability.canSchedule).toBe("boolean");
      // Pinned because the client falls back to "insert a block" on a falsy value: if the
      // engine ever sent a string here, "Move it" would silently start duplicating again.
      expect(typeof settings.capability.canReschedule).toBe("boolean");
      expect(typeof settings.capability.canDraft).toBe("boolean");
      expect(typeof settings.capability.canReadBody).toBe("boolean");
      expect(typeof settings.capability.canSummarize).toBe("boolean");
      // The assistant is described separately from the write mode, because it answers a
      // different question: not what may be done to the account, but where content goes.
      requires(settings.assist, ["enabled", "provider", "contentLeavesMachine", "label"]);
      expect(typeof settings.assist.contentLeavesMachine).toBe("boolean");
    }
    expect(routes["/api/settings"].capability).toEqual({
      canSend: false,
      canSchedule: false,
      canReschedule: false,
      canDraft: false,
      canReadBody: false,
      canSummarize: false,
    });
    // Sample data is nobody's mail, so there is nothing to draft against.
    expect(routes["/api/settings"].assist.enabled).toBe(false);
  });

  // The synthetic fallback used to be invisible: fixtures rendered in the same chrome as real
  // data. `source` is what lets the UI say which day the user is looking at.
  it("/api/settings reports which data source is being served", () => {
    const source = routes["/api/settings"].source;
    requires(source, ["kind", "live", "label"]);
    expect(["connected", "sample"]).toContain(source.kind);
    expect(typeof source.label).toBe("string");
    expect(typeof source.live).toBe("boolean");
    // `live` must agree with `kind`; the client keys its warning off `live`.
    expect(source.live).toBe(source.kind === "connected");
  });
});

describe("the client posts where the engine listens", () => {
  it("sendMail and createEvent exist and are the only write calls", () => {
    // Guards the other direction from the fixture check above: the engine's route list and the
    // client's call surface have to be the same two things.
    expect(typeof api.sendMail).toBe("function");
    expect(typeof api.createEvent).toBe("function");
  });
});
