import Foundation
import XCTest
import DailyPlannerDomain
@testable import DailyPlannerAPI

/// Emits the engine's actual wire contract to a golden file the web test suite reads.
///
/// Three Swift↔TS contract drifts have shipped on this project, each invisible in `npm run dev`
/// because the dev mock sent the client's shape while the engine sent something else. Every layer
/// was unit tested; the seam between the two languages was not. This writes what the engine
/// really encodes — every route's JSON and every finite enum's cases — so the web suite can assert
/// the TypeScript side against it instead of against a hand-maintained mock.
///
/// Run order matters: the Swift suite regenerates this file, then `npm test` checks it.
final class EngineContractFixtureTests: XCTestCase {
    /// Fixed so the golden file is stable between runs and diffs stay readable.
    private let referenceDate = Date(timeIntervalSince1970: 1_789_000_000)

    func testEmitTheEngineContractGoldenFile() async throws {
        let service = PlannerAPIService(referenceDate: referenceDate)

        let routes: [String: Data] = [
            "/api/health": service.health(),
            "/api/preview": try await service.preview(),
            "/api/week": try await service.week(),
            "/api/calendars": try await service.calendars(),
            "/api/settings": service.settingsPayload(),
            "/api/drafts": await service.drafts(),
            "/api/tasks": await service.tasks(),
        ]

        var payloads: [String: Any] = [:]
        for (route, data) in routes {
            payloads[route] = try JSONSerialization.jsonObject(with: data)
        }

        // The synthetic service can only ever emit the read-only shape, so the interesting half
        // of the safety contract — what /api/settings says on a connection that CAN write —
        // would never reach the web suite. Emit it too, from the live initialiser with writers
        // attached, so the TypeScript side pins both states rather than one.
        let writable = PlannerAPIService(
            source: EmptySource(),
            settingsStore: EmptySettings(),
            clock: FixedTestClock(now: referenceDate),
            mailSender: StubSender(),
            eventScheduler: StubScheduler(),
            eventRescheduler: StubMover(),
            capability: .readWrite
        )

        let contract: [String: Any] = [
            "note": "GENERATED by EngineContractFixtureTests. Do not edit by hand.",
            "enums": [
                "category": APICategory.allCases.map(\.rawValue).sorted(),
                "kind": APIKind.allCases.map(\.rawValue).sorted(),
                "calendarRole": APICalendarRole.allCases.map(\.rawValue).sorted(),
                "errorCode": APIErrorCode.allCases.map(\.rawValue).sorted(),
                "writeRoute": APIWriteRoute.allCases.map(\.rawValue).sorted(),
            ],
            "routes": payloads,
            "variants": [
                "settingsWritable": try JSONSerialization.jsonObject(with: writable.settingsPayload()),
            ],
        ]

        let json = try JSONSerialization.data(
            withJSONObject: contract, options: [.prettyPrinted, .sortedKeys]
        )
        let url = Self.fixtureURL()
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true
        )
        try json.write(to: url)

        // Sanity: the file we just wrote is the shape the web suite expects to find.
        XCTAssertTrue(FileManager.default.fileExists(atPath: url.path))
        XCTAssertFalse(APICategory.allCases.isEmpty)
    }

    // MARK: - Minimal stand-ins for the writable variant

    private struct EmptySource: CalendarCatalogReading, PlanningCalendarReading, Sendable {
        func calendars() async throws -> [CalendarDescriptor] { [] }
        func planningEvents(calendarIDs: Set<CalendarID>, interval: DateInterval) async throws -> [PlannerEvent] { [] }
    }

    private struct EmptySettings: PrivateSettingsStore, Sendable {
        func load() throws -> PrivateSettings { .empty }
        func replace(_ settings: PrivateSettings) throws {}
    }

    private struct FixedTestClock: PlannerClock, Sendable {
        let now: Date
    }

    private struct StubSender: PlannerMailSending, Sendable {
        func send(_ mail: PlannerOutgoingMail) async throws -> PlannerSentMail {
            PlannerSentMail(id: "fixture", threadID: nil)
        }
    }

    private struct StubScheduler: PlannerEventScheduling, Sendable {
        func create(_ draft: PlannerEventDraft) async throws -> PlannerScheduledEvent {
            PlannerScheduledEvent(id: "fixture", start: draft.start, end: draft.end, link: nil)
        }
    }

    private struct StubMover: PlannerEventRescheduling, Sendable {
        func move(_ move: PlannerEventMove) async throws -> PlannerScheduledEvent {
            PlannerScheduledEvent(id: move.eventID, start: move.start, end: move.end, link: nil)
        }
    }

    /// `web/src/api/__fixtures__/engine-contract.json`, resolved from this file's own location so
    /// it does not depend on the working directory the suite happens to run in.
    private static func fixtureURL(file: StaticString = #filePath) -> URL {
        // …/DailyPlanner/Tests/DailyPlannerAPITests/EngineContractFixtureTests.swift
        var url = URL(fileURLWithPath: "\(file)")
        for _ in 0..<4 { url.deleteLastPathComponent() }  // -> repo root
        return url
            .appendingPathComponent("web/src/api/__fixtures__/engine-contract.json")
    }
}
